spring:
  # 配置数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.196.131:3307/guilimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: guilimall-coupon
  profiles:
    active: dev
# 配置mybatis-plus
mybatis-plus:
  # 映射文件在哪
  mapper-locations: classpath:/mapper/**/*.xml
  # 自增主键
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000
