spring:
  # 配置数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.196.131:3307/guilimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.196.1:8848
  application:
    name: guilimall-ware
  jackson:
    date-format: yyyy-MM-dd HH:ss:mm

# 配置mybatis-plus
mybatis-plus:
  # 映射文件在哪
  mapper-locations: classpath:/mapper/**/*.xml

  # 自增主键
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000

logging:
  level:
    com.swjtu: debug
