spring:
  application:
    name: guilimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.196.1:8848
    # 配置网关
    gateway:
      routes:
      - id: product_route
        uri: lb://guilimall-product
        predicates:
          - Path=/api/product/**
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

      - id: third_party_route
        uri: lb://guilimall-third-party
        predicates:
          - Path=/api/thirdparty/**
        filters:
          - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

      - id: member_route
        uri: lb://guilimall-member
        predicates:
          - Path=/api/member/**
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

      - id: ware_route
        uri: lb://guilimall-ware
        predicates:
          - Path=/api/ware/**
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

      - id: admin_route
        uri: lb://renren-fast
        predicates:
          - Path=/api/**
        filters:
          - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

      - id: guilimall_host_route
        uri: lb://guilimall-product
        predicates:
          - Host=guilimall.com
      - id: guilimall_search_route
        uri: lb://guilimall-search
        predicates:
          - Host=search.guilimall.com

server:
  port: 88