spring:
  # 配置数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.196.131:3307/guilimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: guilimall-product
  profiles:
    active: dev

# 配置mybatis-plus
mybatis-plus:
  # 映射文件在哪
  mapper-locations: classpath:/mapper/**/*.xml
  # 自增主键
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10001
logging:
  level:
    com.swjtu.guilimall: debug
