spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.196.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: guilimall-ygd
      access-key: LTAI5tRVoQJAAxfkK75VVgWr
      secret-key: mIqtMJ75sXNu7kp8iOdh9GtGFmgsLG
  application:
    name: guilimall-third-party
server:
  port: 30000